# Generated by Django 4.1.5 on 2023-03-01 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('T', 'TRANCE')], max_length=1)),
                ('school', models.CharField(max_length=100)),
                ('join_standard', models.CharField(max_length=100)),
                ('pass_standard', models.CharField(max_length=100)),
                ('favourite_miss', models.CharField(max_length=100)),
                ('pass_or_not', models.BooleanField()),
                ('passby_class', models.CharField(max_length=100)),
                ('passing_parsent', models.IntegerField()),
                ('passby', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023, verbose_name='passby')),
                ('relation_type', models.CharField(max_length=100)),
                ('describe_yourself', models.CharField(max_length=999999)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 3, 1, 15, 54, 14, 154165), null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
