# Generated by Django 4.1.5 on 2023-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addresh', models.CharField(max_length=100)),
                ('imape', models.ImageField(upload_to='')),
            ],
        ),
    ]
