# Generated by Django 4.1.5 on 2023-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageuploder',
            old_name='addresh',
            new_name='address',
        ),
    ]
