# Generated by Django 4.1.5 on 2023-02-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_addresh_imageuploder_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageuploder',
            old_name='imape',
            new_name='image',
        ),
    ]
